services:
  service2:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./service2:/var/tempData
    networks:
      - network_app_service2
      - network_multi
    depends_on:
      - postgreDB_service2
  

  postgreDB_service2:
    image: postgres:14-alpine
    container_name: postgreDB_service2
    restart: unless-stopped
    environment:
      - DB_HOST=postgreDB_service2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - '5431:5432'
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - network_app_service2
networks:
  network_app_service2: 
    driver: bridge